version: 2
updates:
  # Enable version updates for npm (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "@me"
    assignees:
      - "@me"

  # Enable version updates for Cargo (Rust dependencies)
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "@me"
    assignees:
      - "@me"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    assignees:
      - "@me"
