name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Lint frontend (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: npm run lint

      - name: Check Rust formatting (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: cd src-tauri && cargo fmt --all -- --check

      - name: Check Rust code with Clippy (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: cd src-tauri && cargo clippy -- -D warnings

      - name: Build the app
        run: npm run tauri:build ${{ matrix.args }}

      - name: Upload artifacts (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: src-tauri/target/release/bundle/

      - name: Upload artifacts (windows only)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: src-tauri/target/release/bundle/

      - name: Upload artifacts (macos aarch64)
        if: matrix.platform == 'macos-latest' && matrix.args == '--target aarch64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64-artifacts
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/

      - name: Upload artifacts (macos x86_64)
        if: matrix.platform == 'macos-latest' && matrix.args == '--target x86_64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64-artifacts
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/

  create-release:
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create the release
          gh release create ${{ github.ref_name }} \
            --title "BeautifyOllama ${{ github.ref_name }}" \
            --notes "Download the appropriate installer for your platform:
          
          - **Windows**: .msi or .exe file
          - **macOS**: .dmg file (choose Intel or Apple Silicon)  
          - **Linux**: .deb or .AppImage file"

          # Upload all artifacts
          find artifacts -type f \( -name "*.msi" -o -name "*.exe" -o -name "*.dmg" -o -name "*.deb" -o -name "*.AppImage" \) -exec gh release upload ${{ github.ref_name }} {} \;
